<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MarcasSeeder extends Seeder
{
    public function run(): void
    {
        $marcas = [
            ['nombre' => '3M Electrical', 'pais_origen' => null],
            ['nombre' => 'ABB', 'pais_origen' => 'Suiza'],
            ['nombre' => 'ABB Measurement', 'pais_origen' => 'Suiza'],
            ['nombre' => 'Aclara', 'pais_origen' => null],
            ['nombre' => 'AEG', 'pais_origen' => 'Alemania'],
            ['nombre' => 'AEMC', 'pais_origen' => null],
            ['nombre' => 'Alfa Laval', 'pais_origen' => null],
            ['nombre' => 'APC SRT5KXLT', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'APC SURTA3000', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'APC SURTD5000XLT', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Armstrong', 'pais_origen' => null],
            ['nombre' => 'Ashcroft', 'pais_origen' => null],
            ['nombre' => 'Atlas Copco', 'pais_origen' => 'Suecia'],
            ['nombre' => 'Avigilon', 'pais_origen' => null],
            ['nombre' => 'Axis', 'pais_origen' => 'Suecia'],
            ['nombre' => 'Badger Meter', 'pais_origen' => null],
            ['nombre' => 'Baltimore Aircoil', 'pais_origen' => null],
            ['nombre' => 'Barnes', 'pais_origen' => 'Colombia'],
            ['nombre' => 'Belimo', 'pais_origen' => null],
            ['nombre' => 'Bell & Gossett', 'pais_origen' => null],
            ['nombre' => 'BFT', 'pais_origen' => null],
            ['nombre' => 'Big Ass Fans', 'pais_origen' => null],
            ['nombre' => 'Bitzer', 'pais_origen' => null],
            ['nombre' => 'Blue line', 'pais_origen' => null],
            ['nombre' => 'Bosch', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Burndy', 'pais_origen' => null],
            ['nombre' => 'Came', 'pais_origen' => null],
            ['nombre' => 'Carrier', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Caterpillar', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'CCTV Colombia', 'pais_origen' => null],
            ['nombre' => 'Celco', 'pais_origen' => null],
            ['nombre' => 'Chauvin Arnoux', 'pais_origen' => null],
            ['nombre' => 'Chint', 'pais_origen' => null],
            ['nombre' => 'Cooper Lighting', 'pais_origen' => null],
            ['nombre' => 'Copeland', 'pais_origen' => null],
            ['nombre' => 'Cummins', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'CyberPower', 'pais_origen' => null],
            ['nombre' => 'Dahua', 'pais_origen' => 'China'],
            ['nombre' => 'Daikin', 'pais_origen' => 'Japón'],
            ['nombre' => 'Danfoss', 'pais_origen' => 'Dinamarca'],
            ['nombre' => 'DELTEC', 'pais_origen' => null],
            ['nombre' => 'Diehl - Altair', 'pais_origen' => null],
            ['nombre' => 'Dwyer', 'pais_origen' => null],
            ['nombre' => 'Eaton', 'pais_origen' => 'Irlanda'],
            ['nombre' => 'ELSTER', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A 1110', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A 11OO', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A 12OO', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A 1800', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A1100', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A1200', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELSTER A1800', 'pais_origen' => 'Alemania'],
            ['nombre' => 'ELTERS', 'pais_origen' => null],
            ['nombre' => 'ELTERS A 1800', 'pais_origen' => null],
            ['nombre' => 'Emerson', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Endress+Hauser', 'pais_origen' => null],
            ['nombre' => 'Equiprac', 'pais_origen' => null],
            ['nombre' => 'ESAB', 'pais_origen' => null],
            ['nombre' => 'ESTROM', 'pais_origen' => null],
            ['nombre' => 'Evapco', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'FAAC', 'pais_origen' => null],
            ['nombre' => 'FERRUPS', 'pais_origen' => null],
            ['nombre' => 'Flowserve', 'pais_origen' => null],
            ['nombre' => 'Fluke', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Flygt', 'pais_origen' => 'Suecia'],
            ['nombre' => 'Fronius', 'pais_origen' => null],
            ['nombre' => 'Gardner Denver', 'pais_origen' => null],
            ['nombre' => 'GEA', 'pais_origen' => null],
            ['nombre' => 'GENERAL', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'General Electric', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Grundfos', 'pais_origen' => 'Dinamarca'],
            ['nombre' => 'Hach', 'pais_origen' => null],
            ['nombre' => 'Hager', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Hamon', 'pais_origen' => null],
            ['nombre' => 'Hikvision', 'pais_origen' => 'China'],
            ['nombre' => 'Honeywell', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Hubbell', 'pais_origen' => null],
            ['nombre' => 'Hunter', 'pais_origen' => null],
            ['nombre' => 'Hyundai Electric', 'pais_origen' => null],
            ['nombre' => 'Icontec', 'pais_origen' => null],
            ['nombre' => 'IHM', 'pais_origen' => null],
            ['nombre' => 'IHN', 'pais_origen' => null],
            ['nombre' => 'Industrias Estra', 'pais_origen' => null],
            ['nombre' => 'Ingersoll Rand', 'pais_origen' => null],
            ['nombre' => 'INGESER', 'pais_origen' => null],
            ['nombre' => 'INH', 'pais_origen' => null],
            ['nombre' => 'ISKRA', 'pais_origen' => 'Eslovenia'],
            ['nombre' => 'Itron', 'pais_origen' => null],
            ['nombre' => 'ITT Goulds', 'pais_origen' => null],
            ['nombre' => 'John Deere', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Johnson Controls', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Kaeser', 'pais_origen' => null],
            ['nombre' => 'Kamstrup', 'pais_origen' => null],
            ['nombre' => 'kholer', 'pais_origen' => null],
            ['nombre' => 'Kohler (generadores)', 'pais_origen' => null],
            ['nombre' => 'Kruger', 'pais_origen' => null],
            ['nombre' => 'KSB', 'pais_origen' => 'Alemania'],
            ['nombre' => 'LANDIS', 'pais_origen' => 'Suiza'],
            ['nombre' => 'Legrand', 'pais_origen' => 'Francia'],
            ['nombre' => 'LENNOX', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'LG', 'pais_origen' => 'Corea del Sur'],
            ['nombre' => 'Liftmaster', 'pais_origen' => null],
            ['nombre' => 'Lincoln Electric', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'LS Electric', 'pais_origen' => null],
            ['nombre' => 'Lutron', 'pais_origen' => null],
            ['nombre' => 'Magnetron', 'pais_origen' => null],
            ['nombre' => 'Magnetrón S.A.', 'pais_origen' => null],
            ['nombre' => 'MAN Energy', 'pais_origen' => null],
            ['nombre' => 'Marley', 'pais_origen' => null],
            ['nombre' => 'Master Marketing', 'pais_origen' => null],
            ['nombre' => 'Megger', 'pais_origen' => null],
            ['nombre' => 'Miller', 'pais_origen' => null],
            ['nombre' => 'MINUTEMAN', 'pais_origen' => null],
            ['nombre' => 'Mitsubishi Electric', 'pais_origen' => 'Japón'],
            ['nombre' => 'MTU', 'pais_origen' => null],
            ['nombre' => 'Mueller Water', 'pais_origen' => null],
            ['nombre' => 'Nice', 'pais_origen' => null],
            ['nombre' => 'nVent', 'pais_origen' => null],
            ['nombre' => 'Osram', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Panasonic', 'pais_origen' => 'Japón'],
            ['nombre' => 'Pedrollo', 'pais_origen' => 'Italia'],
            ['nombre' => 'Pentair', 'pais_origen' => null],
            ['nombre' => 'Perkins', 'pais_origen' => 'Reino Unido'],
            ['nombre' => 'Philips', 'pais_origen' => 'Países Bajos'],
            ['nombre' => 'Phoenix Contact', 'pais_origen' => null],
            ['nombre' => 'Prometalicos', 'pais_origen' => null],
            ['nombre' => 'Riello', 'pais_origen' => null],
            ['nombre' => 'Rittal', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Roper Technologies', 'pais_origen' => null],
            ['nombre' => 'Rymel', 'pais_origen' => null],
            ['nombre' => 'S&P', 'pais_origen' => null],
            ['nombre' => 'Samsung', 'pais_origen' => 'Corea del Sur'],
            ['nombre' => 'Sappel - Aquila', 'pais_origen' => null],
            ['nombre' => 'Sapper - Altair', 'pais_origen' => null],
            ['nombre' => 'SCHNEIDER ELECTRIC', 'pais_origen' => 'Francia'],
            ['nombre' => 'Sensus', 'pais_origen' => null],
            ['nombre' => 'Siemens', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Siemens Hidromac', 'pais_origen' => 'Alemania'],
            ['nombre' => 'Soler & Palau', 'pais_origen' => null],
            ['nombre' => 'SPX Cooling', 'pais_origen' => null],
            ['nombre' => 'Starlight', 'pais_origen' => null],
            ['nombre' => 'sterllin', 'pais_origen' => null],
            ['nombre' => 'Sulzer', 'pais_origen' => null],
            ['nombre' => 'Sylvania', 'pais_origen' => null],
            ['nombre' => 'Tecam', 'pais_origen' => null],
            ['nombre' => 'Testo', 'pais_origen' => null],
            ['nombre' => 'Thomas & Betts', 'pais_origen' => null],
            ['nombre' => 'TITAN', 'pais_origen' => null],
            ['nombre' => 'TPL', 'pais_origen' => null],
            ['nombre' => 'Trane', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Tripp Lite', 'pais_origen' => null],
            ['nombre' => 'U.S. electric Motors Colbombas', 'pais_origen' => null],
            ['nombre' => 'Vertiv', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'Volvo Penta', 'pais_origen' => null],
            ['nombre' => 'Watts Water', 'pais_origen' => null],
            ['nombre' => 'WEG', 'pais_origen' => 'Brasil'],
            ['nombre' => 'Weidmuller', 'pais_origen' => null],
            ['nombre' => 'Xylem', 'pais_origen' => null],
            ['nombre' => 'Yokogawa', 'pais_origen' => null],
            ['nombre' => 'York', 'pais_origen' => 'Estados Unidos'],
            ['nombre' => 'ZIGOR', 'pais_origen' => 'España'],
            ['nombre' => 'ZKTeco', 'pais_origen' => 'China'],
        ];

        foreach ($marcas as $m) {
            DB::table('marcas')->updateOrInsert(
                ['nombre' => $m['nombre']],
                [
                    'pais_origen' => $m['pais_origen'],
                    'activo'      => true,
                    'created_at'  => now(),
                    'updated_at'  => now(),
                ]
            );
        }
    }
}
